<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class MasterSeeder extends Seeder
{
    public function run(): void
    {
        Schema::disableForeignKeyConstraints();
        // 1. Seed Countries
        if (DB::table('countries')->count() === 0) {
            DB::table('countries')->insert([
                ['name' => 'INDIA', 'code' => 'IN', 'created_at' => now(), 'updated_at' => now()],
            ]);
        }

        $indiaId = DB::table('countries')->where('name', 'INDIA')->value('id');

        // 2. Seed States with GST State Codes and country_id Foreign Key
        if (DB::table('states')->count() === 0) {
            $states = [
                ['country_id' => $indiaId, 'name' => 'JAMMU AND KASHMIR', 'code' => '01', 'short_name' => 'JK'],
                ['country_id' => $indiaId, 'name' => 'HIMACHAL PRADESH', 'code' => '02', 'short_name' => 'HP'],
                ['country_id' => $indiaId, 'name' => 'PUNJAB', 'code' => '03', 'short_name' => 'PB'],
                ['country_id' => $indiaId, 'name' => 'CHANDIGARH', 'code' => '04', 'short_name' => 'CH'],
                ['country_id' => $indiaId, 'name' => 'UTTARAKHAND', 'code' => '05', 'short_name' => 'UK'],
                ['country_id' => $indiaId, 'name' => 'HARYANA', 'code' => '06', 'short_name' => 'HR'],
                ['country_id' => $indiaId, 'name' => 'DELHI', 'code' => '07', 'short_name' => 'DL'],
                ['country_id' => $indiaId, 'name' => 'RAJASTHAN', 'code' => '08', 'short_name' => 'RJ'],
                ['country_id' => $indiaId, 'name' => 'UTTAR PRADESH', 'code' => '09', 'short_name' => 'UP'],
                ['country_id' => $indiaId, 'name' => 'BIHAR', 'code' => '10', 'short_name' => 'BR'],
                ['country_id' => $indiaId, 'name' => 'SIKKIM', 'code' => '11', 'short_name' => 'SK'],
                ['country_id' => $indiaId, 'name' => 'ARUNACHAL PRADESH', 'code' => '12', 'short_name' => 'AR'],
                ['country_id' => $indiaId, 'name' => 'NAGALAND', 'code' => '13', 'short_name' => 'NL'],
                ['country_id' => $indiaId, 'name' => 'MANIPUR', 'code' => '14', 'short_name' => 'MN'],
                ['country_id' => $indiaId, 'name' => 'MIZORAM', 'code' => '15', 'short_name' => 'MZ'],
                ['country_id' => $indiaId, 'name' => 'TRIPURA', 'code' => '16', 'short_name' => 'TR'],
                ['country_id' => $indiaId, 'name' => 'MEGHALAYA', 'code' => '17', 'short_name' => 'ML'],
                ['country_id' => $indiaId, 'name' => 'ASSAM', 'code' => '18', 'short_name' => 'AS'],
                ['country_id' => $indiaId, 'name' => 'WEST BENGAL', 'code' => '19', 'short_name' => 'WB'],
                ['country_id' => $indiaId, 'name' => 'JHARKHAND', 'code' => '20', 'short_name' => 'JH'],
                ['country_id' => $indiaId, 'name' => 'ODISHA', 'code' => '21', 'short_name' => 'OD'],
                ['country_id' => $indiaId, 'name' => 'CHHATTISGARH', 'code' => '22', 'short_name' => 'CG'],
                ['country_id' => $indiaId, 'name' => 'MADHYA PRADESH', 'code' => '23', 'short_name' => 'MP'],
                ['country_id' => $indiaId, 'name' => 'GUJARAT', 'code' => '24', 'short_name' => 'GJ'],
                ['country_id' => $indiaId, 'name' => 'DAMAN AND DIU', 'code' => '25', 'short_name' => 'DD'],
                ['country_id' => $indiaId, 'name' => 'DADRA AND NAGAR HAVELI', 'code' => '26', 'short_name' => 'DN'],
                ['country_id' => $indiaId, 'name' => 'MAHARASHTRA', 'code' => '27', 'short_name' => 'MH'],
                ['country_id' => $indiaId, 'name' => 'ANDHRA PRADESH', 'code' => '37', 'short_name' => 'AP'],
                ['country_id' => $indiaId, 'name' => 'KARNATAKA', 'code' => '29', 'short_name' => 'KA'],
                ['country_id' => $indiaId, 'name' => 'GOA', 'code' => '30', 'short_name' => 'GA'],
                ['country_id' => $indiaId, 'name' => 'LAKSHADWEEP', 'code' => '31', 'short_name' => 'LD'],
                ['country_id' => $indiaId, 'name' => 'KERALA', 'code' => '32', 'short_name' => 'KL'],
                ['country_id' => $indiaId, 'name' => 'TAMIL NADU', 'code' => '33', 'short_name' => 'TN'],
                ['country_id' => $indiaId, 'name' => 'PUDUCHERRY', 'code' => '34', 'short_name' => 'PY'],
                ['country_id' => $indiaId, 'name' => 'ANDAMAN AND NICOBAR ISLANDS', 'code' => '35', 'short_name' => 'AN'],
                ['country_id' => $indiaId, 'name' => 'TELANGANA', 'code' => '36', 'short_name' => 'TS'],
                ['country_id' => $indiaId, 'name' => 'LADAKH', 'code' => '38', 'short_name' => 'LA'],
                ['country_id' => $indiaId, 'name' => 'OTHER TERRITORY', 'code' => '97', 'short_name' => 'OT'],
            ];
            foreach ($states as $s) {
                DB::table('states')->insert(array_merge($s, ['created_at' => now(), 'updated_at' => now()]));
            }
        } else if ($indiaId) {
            DB::table('states')->whereNull('country_id')->update(['country_id' => $indiaId]);
        }

        $stateMap = DB::table('states')->pluck('id', 'name')->toArray();

        // 3. Comprehensive Cities / Logistics Hubs for all States & UTs (including latest renamed cities)
        $allCities = [
            // --- ASSAM (18) ---
            ['name' => 'GUWAHATI', 'short_name' => 'GHY', 'state' => 'ASSAM'],
            ['name' => 'DISPUR', 'short_name' => 'DSP', 'state' => 'ASSAM'],
            ['name' => 'LOKHRA', 'short_name' => 'LKH', 'state' => 'ASSAM'],
            ['name' => 'FANCY BAZAR', 'short_name' => 'FB', 'state' => 'ASSAM'],
            ['name' => 'ATHGAON', 'short_name' => 'ATG', 'state' => 'ASSAM'],
            ['name' => 'AMBARI', 'short_name' => 'AB', 'state' => 'ASSAM'],
            ['name' => 'AMINGAON', 'short_name' => 'AMG', 'state' => 'ASSAM'],
            ['name' => 'AZARA', 'short_name' => 'AZR', 'state' => 'ASSAM'],
            ['name' => 'A.T. ROAD', 'short_name' => 'AT', 'state' => 'ASSAM'],
            ['name' => 'B.BARUAH ROAD', 'short_name' => 'BB', 'state' => 'ASSAM'],
            ['name' => 'TEZPUR', 'short_name' => 'TZP', 'state' => 'ASSAM'],
            ['name' => 'DIBRUGARH', 'short_name' => 'DBR', 'state' => 'ASSAM'],
            ['name' => 'SILCHAR', 'short_name' => 'SLC', 'state' => 'ASSAM'],
            ['name' => 'JORHAT', 'short_name' => 'JRH', 'state' => 'ASSAM'],
            ['name' => 'NAGAON', 'short_name' => 'NGN', 'state' => 'ASSAM'],
            ['name' => 'TINSUKIA', 'short_name' => 'TSK', 'state' => 'ASSAM'],
            ['name' => 'BONGAIGAON', 'short_name' => 'BNG', 'state' => 'ASSAM'],
            ['name' => 'DHUBRI', 'short_name' => 'DHB', 'state' => 'ASSAM'],
            ['name' => 'BARPETA', 'short_name' => 'BRP', 'state' => 'ASSAM'],
            ['name' => 'BARPETA ROAD', 'short_name' => 'BPR', 'state' => 'ASSAM'],
            ['name' => 'NALBARI', 'short_name' => 'NLB', 'state' => 'ASSAM'],
            ['name' => 'RANGIA', 'short_name' => 'RNG', 'state' => 'ASSAM'],
            ['name' => 'MANGALDOI', 'short_name' => 'MGD', 'state' => 'ASSAM'],
            ['name' => 'KHARUPETIA', 'short_name' => 'KHP', 'state' => 'ASSAM'],
            ['name' => 'TANGLA', 'short_name' => 'TGL', 'state' => 'ASSAM'],
            ['name' => 'DHEKIAJULI', 'short_name' => 'DKJ', 'state' => 'ASSAM'],
            ['name' => 'UDALGURI', 'short_name' => 'UDG', 'state' => 'ASSAM'],
            ['name' => 'NORTH LAKHIMPUR', 'short_name' => 'NLP', 'state' => 'ASSAM'],
            ['name' => 'KARIMGANJ', 'short_name' => 'KMG', 'state' => 'ASSAM'],
            ['name' => 'GOLAGHAT', 'short_name' => 'GLG', 'state' => 'ASSAM'],
            ['name' => 'SIVASAGAR', 'short_name' => 'SVG', 'state' => 'ASSAM'],
            ['name' => 'HOJAI', 'short_name' => 'HOJ', 'state' => 'ASSAM'],
            ['name' => 'LANKA', 'short_name' => 'LKA', 'state' => 'ASSAM'],
            ['name' => 'LUMDING', 'short_name' => 'LMG', 'state' => 'ASSAM'],
            ['name' => 'DIPHU', 'short_name' => 'DPH', 'state' => 'ASSAM'],
            ['name' => 'HAFLONG', 'short_name' => 'HFL', 'state' => 'ASSAM'],
            ['name' => 'KOKRAJHAR', 'short_name' => 'KOJ', 'state' => 'ASSAM'],
            ['name' => 'GOALPARA', 'short_name' => 'GLP', 'state' => 'ASSAM'],
            ['name' => 'MORIGAON', 'short_name' => 'MRG', 'state' => 'ASSAM'],
            ['name' => 'BISWANATH CHARIALI', 'short_name' => 'BNC', 'state' => 'ASSAM'],
            ['name' => 'DHEMAJI', 'short_name' => 'DMJ', 'state' => 'ASSAM'],
            ['name' => 'HAILAKANDI', 'short_name' => 'HLK', 'state' => 'ASSAM'],
            ['name' => 'SONARI', 'short_name' => 'SNR', 'state' => 'ASSAM'],
            ['name' => 'CHARAIDEO', 'short_name' => 'CRD', 'state' => 'ASSAM'],
            ['name' => 'HATSINGIMARI', 'short_name' => 'HSM', 'state' => 'ASSAM'],
            ['name' => 'MAJULI', 'short_name' => 'MJL', 'state' => 'ASSAM'],
            ['name' => 'TAMULPUR', 'short_name' => 'TMP', 'state' => 'ASSAM'],
            ['name' => 'BAJALI', 'short_name' => 'BJL', 'state' => 'ASSAM'],
            ['name' => 'PATHSALAL', 'short_name' => 'PSL', 'state' => 'ASSAM'],
            ['name' => 'GOSSAIGAON', 'short_name' => 'GSG', 'state' => 'ASSAM'],
            ['name' => 'BOKAKHAT', 'short_name' => 'BKH', 'state' => 'ASSAM'],
            ['name' => 'MARGHERITA', 'short_name' => 'MRH', 'state' => 'ASSAM'],
            ['name' => 'DOOMDOOMA', 'short_name' => 'DDM', 'state' => 'ASSAM'],
            ['name' => 'DIGBOI', 'short_name' => 'DGB', 'state' => 'ASSAM'],
            ['name' => 'NAZIRA', 'short_name' => 'NZR', 'state' => 'ASSAM'],
            ['name' => 'BADARPUR', 'short_name' => 'BDP', 'state' => 'ASSAM'],

            // --- WEST BENGAL (19) ---
            ['name' => 'KOLKATA', 'short_name' => 'CCU', 'state' => 'WEST BENGAL'],
            ['name' => 'HOWRAH', 'short_name' => 'HWH', 'state' => 'WEST BENGAL'],
            ['name' => 'BURRABAZAR', 'short_name' => 'BBZ', 'state' => 'WEST BENGAL'],
            ['name' => 'DANKUNI', 'short_name' => 'DKN', 'state' => 'WEST BENGAL'],
            ['name' => 'SILIGURI', 'short_name' => 'SLG', 'state' => 'WEST BENGAL'],
            ['name' => 'ASANSOL', 'short_name' => 'ASN', 'state' => 'WEST BENGAL'],
            ['name' => 'DURGAPUR', 'short_name' => 'DGP', 'state' => 'WEST BENGAL'],
            ['name' => 'BARDHAMAN', 'short_name' => 'BDN', 'state' => 'WEST BENGAL'],
            ['name' => 'KHARAGPUR', 'short_name' => 'KGP', 'state' => 'WEST BENGAL'],
            ['name' => 'HALDIA', 'short_name' => 'HLD', 'state' => 'WEST BENGAL'],
            ['name' => 'MALDA', 'short_name' => 'MLD', 'state' => 'WEST BENGAL'],
            ['name' => 'BAHARAMPUR', 'short_name' => 'BHP', 'state' => 'WEST BENGAL'],
            ['name' => 'JALPAIGURI', 'short_name' => 'JPG', 'state' => 'WEST BENGAL'],
            ['name' => 'ALIPURDUAR', 'short_name' => 'APD', 'state' => 'WEST BENGAL'],
            ['name' => 'COOCH BEHAR', 'short_name' => 'COB', 'state' => 'WEST BENGAL'],
            ['name' => 'DARJEELING', 'short_name' => 'DJL', 'state' => 'WEST BENGAL'],
            ['name' => 'KALIMPONG', 'short_name' => 'KMP', 'state' => 'WEST BENGAL'],
            ['name' => 'RAIGANJ', 'short_name' => 'RGJ', 'state' => 'WEST BENGAL'],
            ['name' => 'BALURGHAT', 'short_name' => 'BLG', 'state' => 'WEST BENGAL'],
            ['name' => 'KRISHNANAGAR', 'short_name' => 'KRN', 'state' => 'WEST BENGAL'],
            ['name' => 'NABADWIP', 'short_name' => 'NDP', 'state' => 'WEST BENGAL'],
            ['name' => 'SANTIPUR', 'short_name' => 'STP', 'state' => 'WEST BENGAL'],
            ['name' => 'RANAGHAT', 'short_name' => 'RNG', 'state' => 'WEST BENGAL'],
            ['name' => 'MIDNAPORE', 'short_name' => 'MDN', 'state' => 'WEST BENGAL'],
            ['name' => 'TAMLUK', 'short_name' => 'TMK', 'state' => 'WEST BENGAL'],
            ['name' => 'BANKURA', 'short_name' => 'BNK', 'state' => 'WEST BENGAL'],
            ['name' => 'PURULIA', 'short_name' => 'PRL', 'state' => 'WEST BENGAL'],
            ['name' => 'SURI', 'short_name' => 'SRI', 'state' => 'WEST BENGAL'],
            ['name' => 'BOLPUR', 'short_name' => 'BLP', 'state' => 'WEST BENGAL'],
            ['name' => 'BASIRHAT', 'short_name' => 'BSH', 'state' => 'WEST BENGAL'],
            ['name' => 'HABRA', 'short_name' => 'HBR', 'state' => 'WEST BENGAL'],
            ['name' => 'BARASAT', 'short_name' => 'BST', 'state' => 'WEST BENGAL'],
            ['name' => 'DIAMOND HARBOUR', 'short_name' => 'DHB', 'state' => 'WEST BENGAL'],
            ['name' => 'JANGIPUR', 'short_name' => 'JGP', 'state' => 'WEST BENGAL'],
            ['name' => 'DHULIAN', 'short_name' => 'DHL', 'state' => 'WEST BENGAL'],

            // --- MAHARASHTRA (27) ---
            ['name' => 'MUMBAI', 'short_name' => 'BOM', 'state' => 'MAHARASHTRA'],
            ['name' => 'NAVI MUMBAI', 'short_name' => 'NVM', 'state' => 'MAHARASHTRA'],
            ['name' => 'THANE', 'short_name' => 'THN', 'state' => 'MAHARASHTRA'],
            ['name' => 'KALYAN', 'short_name' => 'KLN', 'state' => 'MAHARASHTRA'],
            ['name' => 'DOMBIVLI', 'short_name' => 'DMB', 'state' => 'MAHARASHTRA'],
            ['name' => 'BHIWANDI', 'short_name' => 'BHW', 'state' => 'MAHARASHTRA'],
            ['name' => 'VASAI', 'short_name' => 'VSI', 'state' => 'MAHARASHTRA'],
            ['name' => 'VIRAR', 'short_name' => 'VRR', 'state' => 'MAHARASHTRA'],
            ['name' => 'PANVEL', 'short_name' => 'PNV', 'state' => 'MAHARASHTRA'],
            ['name' => 'MIRA-BHAYANDAR', 'short_name' => 'MBR', 'state' => 'MAHARASHTRA'],
            ['name' => 'PUNE', 'short_name' => 'PUN', 'state' => 'MAHARASHTRA'],
            ['name' => 'PIMPRI-CHINCHWAD', 'short_name' => 'PCMC', 'state' => 'MAHARASHTRA'],
            ['name' => 'NAGPUR', 'short_name' => 'NAG', 'state' => 'MAHARASHTRA'],
            ['name' => 'NASHIK', 'short_name' => 'NSK', 'state' => 'MAHARASHTRA'],
            ['name' => 'CHHATRAPATI SAMBHAJINAGAR', 'short_name' => 'CSN', 'state' => 'MAHARASHTRA'], // Formerly Aurangabad
            ['name' => 'DHARASHIV', 'short_name' => 'DHS', 'state' => 'MAHARASHTRA'], // Formerly Osmanabad
            ['name' => 'AHILYANAGAR', 'short_name' => 'AHN', 'state' => 'MAHARASHTRA'], // Formerly Ahmednagar
            ['name' => 'SOLAPUR', 'short_name' => 'SLP', 'state' => 'MAHARASHTRA'],
            ['name' => 'KOLHAPUR', 'short_name' => 'KLP', 'state' => 'MAHARASHTRA'],
            ['name' => 'AMRAVATI', 'short_name' => 'AMR', 'state' => 'MAHARASHTRA'],
            ['name' => 'AKOLA', 'short_name' => 'AKL', 'state' => 'MAHARASHTRA'],
            ['name' => 'JALGAON', 'short_name' => 'JLG', 'state' => 'MAHARASHTRA'],
            ['name' => 'LATUR', 'short_name' => 'LTR', 'state' => 'MAHARASHTRA'],
            ['name' => 'DHULE', 'short_name' => 'DHL', 'state' => 'MAHARASHTRA'],
            ['name' => 'CHANDRAPUR', 'short_name' => 'CDP', 'state' => 'MAHARASHTRA'],
            ['name' => 'PARBHANI', 'short_name' => 'PBN', 'state' => 'MAHARASHTRA'],
            ['name' => 'ICHALKARANJI', 'short_name' => 'IKJ', 'state' => 'MAHARASHTRA'],
            ['name' => 'JALNA', 'short_name' => 'JLN', 'state' => 'MAHARASHTRA'],
            ['name' => 'SANGLI', 'short_name' => 'SGL', 'state' => 'MAHARASHTRA'],
            ['name' => 'SATARA', 'short_name' => 'STR', 'state' => 'MAHARASHTRA'],
            ['name' => 'RATNAGIRI', 'short_name' => 'RTG', 'state' => 'MAHARASHTRA'],
            ['name' => 'SINDHUDURG', 'short_name' => 'SND', 'state' => 'MAHARASHTRA'],
            ['name' => 'NANDED', 'short_name' => 'NED', 'state' => 'MAHARASHTRA'],
            ['name' => 'WARDHA', 'short_name' => 'WRD', 'state' => 'MAHARASHTRA'],
            ['name' => 'GONDIYA', 'short_name' => 'GND', 'state' => 'MAHARASHTRA'],
            ['name' => 'BHANDARA', 'short_name' => 'BHD', 'state' => 'MAHARASHTRA'],
            ['name' => 'YAVATMAL', 'short_name' => 'YTL', 'state' => 'MAHARASHTRA'],
            ['name' => 'WASHIM', 'short_name' => 'WSM', 'state' => 'MAHARASHTRA'],
            ['name' => 'BULDHANA', 'short_name' => 'BLD', 'state' => 'MAHARASHTRA'],
            ['name' => 'NANDURBAR', 'short_name' => 'NDB', 'state' => 'MAHARASHTRA'],
            ['name' => 'GADCHIROLI', 'short_name' => 'GDC', 'state' => 'MAHARASHTRA'],
            ['name' => 'PALGHAR', 'short_name' => 'PLG', 'state' => 'MAHARASHTRA'],

            // --- DELHI (07) ---
            ['name' => 'DELHI', 'short_name' => 'DEL', 'state' => 'DELHI'],
            ['name' => 'NEW DELHI', 'short_name' => 'NDL', 'state' => 'DELHI'],
            ['name' => 'NORTH DELHI', 'short_name' => 'ND', 'state' => 'DELHI'],
            ['name' => 'SOUTH DELHI', 'short_name' => 'SD', 'state' => 'DELHI'],
            ['name' => 'EAST DELHI', 'short_name' => 'ED', 'state' => 'DELHI'],
            ['name' => 'WEST DELHI', 'short_name' => 'WD', 'state' => 'DELHI'],
            ['name' => 'CHANDNI CHOWK', 'short_name' => 'CC', 'state' => 'DELHI'],
            ['name' => 'CONNAUGHT PLACE', 'short_name' => 'CP', 'state' => 'DELHI'],
            ['name' => 'KAROL BAGH', 'short_name' => 'KB', 'state' => 'DELHI'],
            ['name' => 'OKHLA', 'short_name' => 'OKH', 'state' => 'DELHI'],
            ['name' => 'DWARKA', 'short_name' => 'DWK', 'state' => 'DELHI'],
            ['name' => 'ROHINI', 'short_name' => 'RHN', 'state' => 'DELHI'],
            ['name' => 'PITAMPURA', 'short_name' => 'PTP', 'state' => 'DELHI'],
            ['name' => 'JANAKPURI', 'short_name' => 'JNK', 'state' => 'DELHI'],
            ['name' => 'LAXMI NAGAR', 'short_name' => 'LXN', 'state' => 'DELHI'],
            ['name' => 'SHAHDARA', 'short_name' => 'SHD', 'state' => 'DELHI'],
            ['name' => 'NARELA', 'short_name' => 'NRL', 'state' => 'DELHI'],
            ['name' => 'BAWANA', 'short_name' => 'BWN', 'state' => 'DELHI'],
            ['name' => 'AZADPUR', 'short_name' => 'AZP', 'state' => 'DELHI'],

            // --- UTTAR PRADESH (09) ---
            ['name' => 'LUCKNOW', 'short_name' => 'LKO', 'state' => 'UTTAR PRADESH'],
            ['name' => 'KANPUR', 'short_name' => 'KNP', 'state' => 'UTTAR PRADESH'],
            ['name' => 'PRAYAGRAJ', 'short_name' => 'PRG', 'state' => 'UTTAR PRADESH'], // Formerly Allahabad
            ['name' => 'VARANASI', 'short_name' => 'VNS', 'state' => 'UTTAR PRADESH'],
            ['name' => 'AYODHYA', 'short_name' => 'AYD', 'state' => 'UTTAR PRADESH'], // Formerly Faizabad
            ['name' => 'AGRA', 'short_name' => 'AGR', 'state' => 'UTTAR PRADESH'],
            ['name' => 'ALIGARH', 'short_name' => 'ALG', 'state' => 'UTTAR PRADESH'],
            ['name' => 'BAREILLY', 'short_name' => 'BLY', 'state' => 'UTTAR PRADESH'],
            ['name' => 'MEERUT', 'short_name' => 'MRT', 'state' => 'UTTAR PRADESH'],
            ['name' => 'MORADABAD', 'short_name' => 'MBD', 'state' => 'UTTAR PRADESH'],
            ['name' => 'GORAKHPUR', 'short_name' => 'GKP', 'state' => 'UTTAR PRADESH'],
            ['name' => 'SAHARANPUR', 'short_name' => 'SRE', 'state' => 'UTTAR PRADESH'],
            ['name' => 'JHANSI', 'short_name' => 'JHS', 'state' => 'UTTAR PRADESH'],
            ['name' => 'MATHURA', 'short_name' => 'MTR', 'state' => 'UTTAR PRADESH'],
            ['name' => 'FIROZABAD', 'short_name' => 'FZD', 'state' => 'UTTAR PRADESH'],
            ['name' => 'GHAZIABAD', 'short_name' => 'GZB', 'state' => 'UTTAR PRADESH'],
            ['name' => 'NOIDA', 'short_name' => 'NOI', 'state' => 'UTTAR PRADESH'],
            ['name' => 'GREATER NOIDA', 'short_name' => 'GNOI', 'state' => 'UTTAR PRADESH'],
            ['name' => 'MUZAFFARNAGAR', 'short_name' => 'MZN', 'state' => 'UTTAR PRADESH'],
            ['name' => 'BADAUN', 'short_name' => 'BDN', 'state' => 'UTTAR PRADESH'],
            ['name' => 'RAMPUR', 'short_name' => 'RMP', 'state' => 'UTTAR PRADESH'],
            ['name' => 'SHAHJAHANPUR', 'short_name' => 'SJP', 'state' => 'UTTAR PRADESH'],
            ['name' => 'FARRUKHABAD', 'short_name' => 'FKD', 'state' => 'UTTAR PRADESH'],
            ['name' => 'HAPUR', 'short_name' => 'HPR', 'state' => 'UTTAR PRADESH'],
            ['name' => 'ETAWAH', 'short_name' => 'ETW', 'state' => 'UTTAR PRADESH'],
            ['name' => 'MIRZAPUR', 'short_name' => 'MZP', 'state' => 'UTTAR PRADESH'],
            ['name' => 'BULANDSHAHR', 'short_name' => 'BSH', 'state' => 'UTTAR PRADESH'],
            ['name' => 'SAMBHAL', 'short_name' => 'SMB', 'state' => 'UTTAR PRADESH'],
            ['name' => 'AMROHA', 'short_name' => 'AMR', 'state' => 'UTTAR PRADESH'],
            ['name' => 'HARDOI', 'short_name' => 'HRD', 'state' => 'UTTAR PRADESH'],
            ['name' => 'FATEHPUR', 'short_name' => 'FTP', 'state' => 'UTTAR PRADESH'],
            ['name' => 'RAEBARELI', 'short_name' => 'RBL', 'state' => 'UTTAR PRADESH'],
            ['name' => 'ORAI', 'short_name' => 'ORI', 'state' => 'UTTAR PRADESH'],
            ['name' => 'SITAPUR', 'short_name' => 'STP', 'state' => 'UTTAR PRADESH'],
            ['name' => 'BAHRAICH', 'short_name' => 'BRH', 'state' => 'UTTAR PRADESH'],
            ['name' => 'MODINAGAR', 'short_name' => 'MDN', 'state' => 'UTTAR PRADESH'],
            ['name' => 'UNNAO', 'short_name' => 'UNN', 'state' => 'UTTAR PRADESH'],
            ['name' => 'JAUNPUR', 'short_name' => 'JNP', 'state' => 'UTTAR PRADESH'],
            ['name' => 'LAKHIMPUR', 'short_name' => 'LKP', 'state' => 'UTTAR PRADESH'],
            ['name' => 'HATHRAS', 'short_name' => 'HTR', 'state' => 'UTTAR PRADESH'],
            ['name' => 'BANDA', 'short_name' => 'BND', 'state' => 'UTTAR PRADESH'],
            ['name' => 'PILIBHIT', 'short_name' => 'PBT', 'state' => 'UTTAR PRADESH'],
            ['name' => 'BARABANKI', 'short_name' => 'BBK', 'state' => 'UTTAR PRADESH'],
            ['name' => 'PT. DEEN DAYAL UPADHYAYA NAGAR', 'short_name' => 'DDU', 'state' => 'UTTAR PRADESH'], // Formerly Mughalsarai
            ['name' => 'GONDA', 'short_name' => 'GND', 'state' => 'UTTAR PRADESH'],
            ['name' => 'BASTI', 'short_name' => 'BST', 'state' => 'UTTAR PRADESH'],
            ['name' => 'DEORIA', 'short_name' => 'DER', 'state' => 'UTTAR PRADESH'],
            ['name' => 'GHAZIPUR', 'short_name' => 'GZP', 'state' => 'UTTAR PRADESH'],
            ['name' => 'SULTANPUR', 'short_name' => 'SLN', 'state' => 'UTTAR PRADESH'],
            ['name' => 'AZAMGARH', 'short_name' => 'AZM', 'state' => 'UTTAR PRADESH'],
            ['name' => 'BIJNOR', 'short_name' => 'BJN', 'state' => 'UTTAR PRADESH'],
            ['name' => 'BALLIA', 'short_name' => 'BLL', 'state' => 'UTTAR PRADESH'],
            ['name' => 'SHAMLI', 'short_name' => 'SML', 'state' => 'UTTAR PRADESH'],
            ['name' => 'KASGANJ', 'short_name' => 'KSG', 'state' => 'UTTAR PRADESH'],
            ['name' => 'MAINPURI', 'short_name' => 'MNP', 'state' => 'UTTAR PRADESH'],

            // --- BIHAR (10) ---
            ['name' => 'PATNA', 'short_name' => 'PAT', 'state' => 'BIHAR'],
            ['name' => 'GAYA', 'short_name' => 'GAY', 'state' => 'BIHAR'],
            ['name' => 'BHAGALPUR', 'short_name' => 'BGP', 'state' => 'BIHAR'],
            ['name' => 'MUZAFFARPUR', 'short_name' => 'MUZ', 'state' => 'BIHAR'],
            ['name' => 'PURNIA', 'short_name' => 'PRN', 'state' => 'BIHAR'],
            ['name' => 'DARBHANGA', 'short_name' => 'DBG', 'state' => 'BIHAR'],
            ['name' => 'BIHAR SHARIF', 'short_name' => 'BSF', 'state' => 'BIHAR'],
            ['name' => 'ARRAH', 'short_name' => 'ARA', 'state' => 'BIHAR'],
            ['name' => 'BEGUSARAI', 'short_name' => 'BGS', 'state' => 'BIHAR'],
            ['name' => 'KATIHAR', 'short_name' => 'KTR', 'state' => 'BIHAR'],
            ['name' => 'MUNGER', 'short_name' => 'MGR', 'state' => 'BIHAR'],
            ['name' => 'CHHAPRA', 'short_name' => 'CPR', 'state' => 'BIHAR'],
            ['name' => 'DANAPUR', 'short_name' => 'DNR', 'state' => 'BIHAR'],
            ['name' => 'BETTIAH', 'short_name' => 'BTH', 'state' => 'BIHAR'],
            ['name' => 'SAHARSA', 'short_name' => 'SHS', 'state' => 'BIHAR'],
            ['name' => 'SASARAM', 'short_name' => 'SSM', 'state' => 'BIHAR'],
            ['name' => 'HAJIPUR', 'short_name' => 'HJP', 'state' => 'BIHAR'],
            ['name' => 'DEHRI', 'short_name' => 'DOS', 'state' => 'BIHAR'],
            ['name' => 'SIWAN', 'short_name' => 'SWN', 'state' => 'BIHAR'],
            ['name' => 'MOTIHARI', 'short_name' => 'MTH', 'state' => 'BIHAR'],
            ['name' => 'NAWADA', 'short_name' => 'NWD', 'state' => 'BIHAR'],
            ['name' => 'BAGAHA', 'short_name' => 'BGH', 'state' => 'BIHAR'],
            ['name' => 'BUXAR', 'short_name' => 'BXR', 'state' => 'BIHAR'],
            ['name' => 'KISHANGANJ', 'short_name' => 'KSG', 'state' => 'BIHAR'],
            ['name' => 'SITAMARHI', 'short_name' => 'STM', 'state' => 'BIHAR'],
            ['name' => 'JAMALPUR', 'short_name' => 'JMP', 'state' => 'BIHAR'],
            ['name' => 'JEHANABAD', 'short_name' => 'JHD', 'state' => 'BIHAR'],
            ['name' => 'AURANGABAD (BIHAR)', 'short_name' => 'AGB', 'state' => 'BIHAR'],
            ['name' => 'LAKHISARAI', 'short_name' => 'LKS', 'state' => 'BIHAR'],
            ['name' => 'MADHUBANI', 'short_name' => 'MDB', 'state' => 'BIHAR'],
            ['name' => 'SAMASTIPUR', 'short_name' => 'SMP', 'state' => 'BIHAR'],
            ['name' => 'SUPAUL', 'short_name' => 'SPL', 'state' => 'BIHAR'],
            ['name' => 'GOPALGANJ', 'short_name' => 'GPG', 'state' => 'BIHAR'],
            ['name' => 'BHABUA', 'short_name' => 'BHB', 'state' => 'BIHAR'],
            ['name' => 'KHAGARIA', 'short_name' => 'KHG', 'state' => 'BIHAR'],
            ['name' => 'ARARIA', 'short_name' => 'ARR', 'state' => 'BIHAR'],
            ['name' => 'MADHEPURA', 'short_name' => 'MDP', 'state' => 'BIHAR'],
            ['name' => 'FORBESGANJ', 'short_name' => 'FBG', 'state' => 'BIHAR'],
            ['name' => 'RAXAUL', 'short_name' => 'RXL', 'state' => 'BIHAR'],

            // --- GUJARAT (24) ---
            ['name' => 'AHMEDABAD', 'short_name' => 'AMD', 'state' => 'GUJARAT'],
            ['name' => 'SURAT', 'short_name' => 'SUR', 'state' => 'GUJARAT'],
            ['name' => 'VADODARA', 'short_name' => 'BRD', 'state' => 'GUJARAT'],
            ['name' => 'RAJKOT', 'short_name' => 'RAJ', 'state' => 'GUJARAT'],
            ['name' => 'BHAVNAGAR', 'short_name' => 'BHV', 'state' => 'GUJARAT'],
            ['name' => 'JAMNAGAR', 'short_name' => 'JAM', 'state' => 'GUJARAT'],
            ['name' => 'JUNAGADH', 'short_name' => 'JND', 'state' => 'GUJARAT'],
            ['name' => 'GANDHINAGAR', 'short_name' => 'GDN', 'state' => 'GUJARAT'],
            ['name' => 'GANDHIDHAM', 'short_name' => 'GDM', 'state' => 'GUJARAT'],
            ['name' => 'ANAND', 'short_name' => 'AND', 'state' => 'GUJARAT'],
            ['name' => 'NAVSARI', 'short_name' => 'NVS', 'state' => 'GUJARAT'],
            ['name' => 'MORBI', 'short_name' => 'MRB', 'state' => 'GUJARAT'],
            ['name' => 'NADIAD', 'short_name' => 'NDD', 'state' => 'GUJARAT'],
            ['name' => 'SURENDRANAGAR', 'short_name' => 'SRN', 'state' => 'GUJARAT'],
            ['name' => 'BHARUCH', 'short_name' => 'BRC', 'state' => 'GUJARAT'],
            ['name' => 'ANKLESHWAR', 'short_name' => 'AKW', 'state' => 'GUJARAT'],
            ['name' => 'MEHSANA', 'short_name' => 'MSN', 'state' => 'GUJARAT'],
            ['name' => 'BHUJ', 'short_name' => 'BHJ', 'state' => 'GUJARAT'],
            ['name' => 'MUNDRA', 'short_name' => 'MND', 'state' => 'GUJARAT'],
            ['name' => 'KANDLA', 'short_name' => 'KDL', 'state' => 'GUJARAT'],
            ['name' => 'PORBANDAR', 'short_name' => 'PBD', 'state' => 'GUJARAT'],
            ['name' => 'PALANPUR', 'short_name' => 'PLP', 'state' => 'GUJARAT'],
            ['name' => 'VALSAD', 'short_name' => 'VSD', 'state' => 'GUJARAT'],
            ['name' => 'VAPI', 'short_name' => 'VPI', 'state' => 'GUJARAT'],
            ['name' => 'GONDAL', 'short_name' => 'GDL', 'state' => 'GUJARAT'],
            ['name' => 'VERAVAL', 'short_name' => 'VRL', 'state' => 'GUJARAT'],
            ['name' => 'GODHRA', 'short_name' => 'GDH', 'state' => 'GUJARAT'],
            ['name' => 'PATAN', 'short_name' => 'PTN', 'state' => 'GUJARAT'],
            ['name' => 'KALOL', 'short_name' => 'KLL', 'state' => 'GUJARAT'],
            ['name' => 'DAHOD', 'short_name' => 'DHD', 'state' => 'GUJARAT'],
            ['name' => 'BOTAD', 'short_name' => 'BTD', 'state' => 'GUJARAT'],
            ['name' => 'AMRELI', 'short_name' => 'AMR', 'state' => 'GUJARAT'],
            ['name' => 'DEESA', 'short_name' => 'DES', 'state' => 'GUJARAT'],
            ['name' => 'JETPUR', 'short_name' => 'JTP', 'state' => 'GUJARAT'],

            // --- RAJASTHAN (08) ---
            ['name' => 'JAIPUR', 'short_name' => 'JAI', 'state' => 'RAJASTHAN'],
            ['name' => 'JODHPUR', 'short_name' => 'JDH', 'state' => 'RAJASTHAN'],
            ['name' => 'KOTA', 'short_name' => 'KTA', 'state' => 'RAJASTHAN'],
            ['name' => 'BIKANER', 'short_name' => 'BKN', 'state' => 'RAJASTHAN'],
            ['name' => 'AJMER', 'short_name' => 'AJM', 'state' => 'RAJASTHAN'],
            ['name' => 'UDAIPUR', 'short_name' => 'UDR', 'state' => 'RAJASTHAN'],
            ['name' => 'BHILWARA', 'short_name' => 'BHL', 'state' => 'RAJASTHAN'],
            ['name' => 'ALWAR', 'short_name' => 'ALW', 'state' => 'RAJASTHAN'],
            ['name' => 'BHIWADI', 'short_name' => 'BHD', 'state' => 'RAJASTHAN'],
            ['name' => 'BHARATPUR', 'short_name' => 'BHT', 'state' => 'RAJASTHAN'],
            ['name' => 'SIKAR', 'short_name' => 'SKR', 'state' => 'RAJASTHAN'],
            ['name' => 'PALI', 'short_name' => 'PLI', 'state' => 'RAJASTHAN'],
            ['name' => 'SRI GANGANAGAR', 'short_name' => 'SGN', 'state' => 'RAJASTHAN'],
            ['name' => 'BEAWAR', 'short_name' => 'BWR', 'state' => 'RAJASTHAN'],
            ['name' => 'HANUMANGARH', 'short_name' => 'HNM', 'state' => 'RAJASTHAN'],
            ['name' => 'TONK', 'short_name' => 'TNK', 'state' => 'RAJASTHAN'],
            ['name' => 'KISHANGARH', 'short_name' => 'KSG', 'state' => 'RAJASTHAN'],
            ['name' => 'JHUNJHUNU', 'short_name' => 'JJN', 'state' => 'RAJASTHAN'],
            ['name' => 'BANSWARA', 'short_name' => 'BSW', 'state' => 'RAJASTHAN'],
            ['name' => 'CHITTORGARH', 'short_name' => 'COR', 'state' => 'RAJASTHAN'],
            ['name' => 'BUNDI', 'short_name' => 'BND', 'state' => 'RAJASTHAN'],
            ['name' => 'BARAN', 'short_name' => 'BRN', 'state' => 'RAJASTHAN'],
            ['name' => 'DAUSA', 'short_name' => 'DSA', 'state' => 'RAJASTHAN'],
            ['name' => 'NAGAUR', 'short_name' => 'NGR', 'state' => 'RAJASTHAN'],
            ['name' => 'SAWAI MADHOPUR', 'short_name' => 'SWM', 'state' => 'RAJASTHAN'],
            ['name' => 'CHURU', 'short_name' => 'CRU', 'state' => 'RAJASTHAN'],
            ['name' => 'DHOLPUR', 'short_name' => 'DHP', 'state' => 'RAJASTHAN'],
            ['name' => 'JHALAWAR', 'short_name' => 'JHW', 'state' => 'RAJASTHAN'],
            ['name' => 'DUNGARPUR', 'short_name' => 'DGP', 'state' => 'RAJASTHAN'],
            ['name' => 'JAISALMER', 'short_name' => 'JSL', 'state' => 'RAJASTHAN'],
            ['name' => 'RAJSAMAND', 'short_name' => 'RSM', 'state' => 'RAJASTHAN'],
            ['name' => 'BARMER', 'short_name' => 'BMR', 'state' => 'RAJASTHAN'],
            ['name' => 'BALOTRA', 'short_name' => 'BLT', 'state' => 'RAJASTHAN'],
            ['name' => 'NEEM KA THANA', 'short_name' => 'NKT', 'state' => 'RAJASTHAN'],
            ['name' => 'KOTPUTLI', 'short_name' => 'KTP', 'state' => 'RAJASTHAN'],

            // --- KARNATAKA (29) ---
            ['name' => 'BENGALURU', 'short_name' => 'BLR', 'state' => 'KARNATAKA'], // Formerly Bangalore
            ['name' => 'MYSURU', 'short_name' => 'MYS', 'state' => 'KARNATAKA'], // Formerly Mysore
            ['name' => 'HUBBALLI', 'short_name' => 'HBX', 'state' => 'KARNATAKA'], // Formerly Hubli
            ['name' => 'DHARWAD', 'short_name' => 'DWR', 'state' => 'KARNATAKA'],
            ['name' => 'MANGALURU', 'short_name' => 'IXE', 'state' => 'KARNATAKA'], // Formerly Mangalore
            ['name' => 'BELAGAVI', 'short_name' => 'IXG', 'state' => 'KARNATAKA'], // Formerly Belgaum
            ['name' => 'KALABURAGI', 'short_name' => 'KLB', 'state' => 'KARNATAKA'], // Formerly Gulbarga
            ['name' => 'DAVANAGERE', 'short_name' => 'DVG', 'state' => 'KARNATAKA'],
            ['name' => 'BALLARI', 'short_name' => 'BLR', 'state' => 'KARNATAKA'], // Formerly Bellary
            ['name' => 'VIJAYAPURA', 'short_name' => 'VJP', 'state' => 'KARNATAKA'], // Formerly Bijapur
            ['name' => 'SHIVAMOGGA', 'short_name' => 'SMG', 'state' => 'KARNATAKA'], // Formerly Shimoga
            ['name' => 'TUMAKURU', 'short_name' => 'TMK', 'state' => 'KARNATAKA'], // Formerly Tumkur
            ['name' => 'RAICHUR', 'short_name' => 'RCR', 'state' => 'KARNATAKA'],
            ['name' => 'BIDAR', 'short_name' => 'BDR', 'state' => 'KARNATAKA'],
            ['name' => 'HOSAPETE', 'short_name' => 'HPT', 'state' => 'KARNATAKA'], // Formerly Hospet
            ['name' => 'GADAG', 'short_name' => 'GDG', 'state' => 'KARNATAKA'],
            ['name' => 'HASSAN', 'short_name' => 'HSN', 'state' => 'KARNATAKA'],
            ['name' => 'BHADRAVATI', 'short_name' => 'BDV', 'state' => 'KARNATAKA'],
            ['name' => 'CHITRADURGA', 'short_name' => 'CTA', 'state' => 'KARNATAKA'],
            ['name' => 'UDUPI', 'short_name' => 'UDP', 'state' => 'KARNATAKA'],
            ['name' => 'KOLAR', 'short_name' => 'KLR', 'state' => 'KARNATAKA'],
            ['name' => 'MANDYA', 'short_name' => 'MYA', 'state' => 'KARNATAKA'],
            ['name' => 'CHIKKAMAGALURU', 'short_name' => 'CKM', 'state' => 'KARNATAKA'],
            ['name' => 'BAGALKOTE', 'short_name' => 'BGK', 'state' => 'KARNATAKA'],
            ['name' => 'KARWAR', 'short_name' => 'KRW', 'state' => 'KARNATAKA'],
            ['name' => 'MADIKERI', 'short_name' => 'MDK', 'state' => 'KARNATAKA'], // Coorg

            // --- TAMIL NADU (33) ---
            ['name' => 'CHENNAI', 'short_name' => 'MAA', 'state' => 'TAMIL NADU'],
            ['name' => 'COIMBATORE', 'short_name' => 'CJB', 'state' => 'TAMIL NADU'],
            ['name' => 'MADURAI', 'short_name' => 'IXM', 'state' => 'TAMIL NADU'],
            ['name' => 'TIRUCHIRAPPALLI', 'short_name' => 'TRZ', 'state' => 'TAMIL NADU'], // Trichy
            ['name' => 'SALEM', 'short_name' => 'SLM', 'state' => 'TAMIL NADU'],
            ['name' => 'TIRUPPUR', 'short_name' => 'TPR', 'state' => 'TAMIL NADU'],
            ['name' => 'ERODE', 'short_name' => 'ERD', 'state' => 'TAMIL NADU'],
            ['name' => 'TIRUNELVELI', 'short_name' => 'TNV', 'state' => 'TAMIL NADU'],
            ['name' => 'VELLORE', 'short_name' => 'VLR', 'state' => 'TAMIL NADU'],
            ['name' => 'THOOTHUKUDI', 'short_name' => 'TCR', 'state' => 'TAMIL NADU'], // Tuticorin
            ['name' => 'DINDIGUL', 'short_name' => 'DGL', 'state' => 'TAMIL NADU'],
            ['name' => 'THANJAVUR', 'short_name' => 'TNJ', 'state' => 'TAMIL NADU'],
            ['name' => 'RANIPET', 'short_name' => 'RPT', 'state' => 'TAMIL NADU'],
            ['name' => 'SIVAKASI', 'short_name' => 'SVK', 'state' => 'TAMIL NADU'],
            ['name' => 'KARUR', 'short_name' => 'KRR', 'state' => 'TAMIL NADU'],
            ['name' => 'UDHAGAMANDALAM', 'short_name' => 'OOT', 'state' => 'TAMIL NADU'], // Ooty
            ['name' => 'HOSUR', 'short_name' => 'HSR', 'state' => 'TAMIL NADU'],
            ['name' => 'NAGERCOIL', 'short_name' => 'NCJ', 'state' => 'TAMIL NADU'],
            ['name' => 'KANCHIPURAM', 'short_name' => 'KPM', 'state' => 'TAMIL NADU'],
            ['name' => 'CUDDALORE', 'short_name' => 'CDL', 'state' => 'TAMIL NADU'],
            ['name' => 'KUMBAKONAM', 'short_name' => 'KMU', 'state' => 'TAMIL NADU'],
            ['name' => 'TIRUVANNAMALAI', 'short_name' => 'TNM', 'state' => 'TAMIL NADU'],
            ['name' => 'POLLACHI', 'short_name' => 'POY', 'state' => 'TAMIL NADU'],
            ['name' => 'PUDUKKOTTAI', 'short_name' => 'PDK', 'state' => 'TAMIL NADU'],
            ['name' => 'NAGAPATTINAM', 'short_name' => 'NGT', 'state' => 'TAMIL NADU'],
            ['name' => 'VILLUPURAM', 'short_name' => 'VPM', 'state' => 'TAMIL NADU'],
            ['name' => 'THENI', 'short_name' => 'THN', 'state' => 'TAMIL NADU'],
            ['name' => 'TENKASI', 'short_name' => 'TSI', 'state' => 'TAMIL NADU'],
            ['name' => 'DHARMAPURI', 'short_name' => 'DPI', 'state' => 'TAMIL NADU'],
            ['name' => 'KRISHNAGIRI', 'short_name' => 'KGI', 'state' => 'TAMIL NADU'],
            ['name' => 'NAMAKKAL', 'short_name' => 'NMK', 'state' => 'TAMIL NADU'],
            ['name' => 'RAMANATHAPURAM', 'short_name' => 'RMD', 'state' => 'TAMIL NADU'],

            // --- TELANGANA (36) ---
            ['name' => 'HYDERABAD', 'short_name' => 'HYD', 'state' => 'TELANGANA'],
            ['name' => 'SECUNDERABAD', 'short_name' => 'SC', 'state' => 'TELANGANA'],
            ['name' => 'WARANGAL', 'short_name' => 'WGL', 'state' => 'TELANGANA'],
            ['name' => 'NIZAMABAD', 'short_name' => 'NZB', 'state' => 'TELANGANA'],
            ['name' => 'KHAMMAM', 'short_name' => 'KMM', 'state' => 'TELANGANA'],
            ['name' => 'KARIMNAGAR', 'short_name' => 'KRMR', 'state' => 'TELANGANA'],
            ['name' => 'RAMAGUNDAM', 'short_name' => 'RDM', 'state' => 'TELANGANA'],
            ['name' => 'MAHBUBNAGAR', 'short_name' => 'MBNR', 'state' => 'TELANGANA'],
            ['name' => 'NALGONDA', 'short_name' => 'NLG', 'state' => 'TELANGANA'],
            ['name' => 'ADILABAD', 'short_name' => 'ADB', 'state' => 'TELANGANA'],
            ['name' => 'SURYAPET', 'short_name' => 'SYP', 'state' => 'TELANGANA'],
            ['name' => 'SIDDIPET', 'short_name' => 'SDP', 'state' => 'TELANGANA'],
            ['name' => 'MANCHERIAL', 'short_name' => 'MCI', 'state' => 'TELANGANA'],
            ['name' => 'SANGAREDDY', 'short_name' => 'SRD', 'state' => 'TELANGANA'],
            ['name' => 'KOTHAGUDEM', 'short_name' => 'KGM', 'state' => 'TELANGANA'],
            ['name' => 'JAGTIAL', 'short_name' => 'JGT', 'state' => 'TELANGANA'],
            ['name' => 'NIRMAL', 'short_name' => 'NRM', 'state' => 'TELANGANA'],
            ['name' => 'KAMAREDDY', 'short_name' => 'KMR', 'state' => 'TELANGANA'],

            // --- ANDHRA PRADESH (37) ---
            ['name' => 'VISAKHAPATNAM', 'short_name' => 'VTZ', 'state' => 'ANDHRA PRADESH'], // Vizag
            ['name' => 'VIJAYAWADA', 'short_name' => 'BZA', 'state' => 'ANDHRA PRADESH'],
            ['name' => 'GUNTUR', 'short_name' => 'GNT', 'state' => 'ANDHRA PRADESH'],
            ['name' => 'NELLORE', 'short_name' => 'NLR', 'state' => 'ANDHRA PRADESH'],
            ['name' => 'KURNOOL', 'short_name' => 'KRNL', 'state' => 'ANDHRA PRADESH'],
            ['name' => 'KAKINADA', 'short_name' => 'CCT', 'state' => 'ANDHRA PRADESH'],
            ['name' => 'RAJAMAHENDRAVARAM', 'short_name' => 'RJY', 'state' => 'ANDHRA PRADESH'], // Formerly Rajahmundry
            ['name' => 'KADAPA', 'short_name' => 'CDP', 'state' => 'ANDHRA PRADESH'],
            ['name' => 'TIRUPATI', 'short_name' => 'TPTY', 'state' => 'ANDHRA PRADESH'],
            ['name' => 'ANANTAPUR', 'short_name' => 'ATP', 'state' => 'ANDHRA PRADESH'],
            ['name' => 'VIZIANAGARAM', 'short_name' => 'VZM', 'state' => 'ANDHRA PRADESH'],
            ['name' => 'ELURU', 'short_name' => 'EE', 'state' => 'ANDHRA PRADESH'],
            ['name' => 'NANDYAL', 'short_name' => 'NDL', 'state' => 'ANDHRA PRADESH'],
            ['name' => 'ONGOLE', 'short_name' => 'OGL', 'state' => 'ANDHRA PRADESH'],
            ['name' => 'MACHILIPATNAM', 'short_name' => 'MTM', 'state' => 'ANDHRA PRADESH'],
            ['name' => 'CHITTOOR', 'short_name' => 'CTO', 'state' => 'ANDHRA PRADESH'],
            ['name' => 'BHIMAVARAM', 'short_name' => 'BVRM', 'state' => 'ANDHRA PRADESH'],
            ['name' => 'SRIKAKULAM', 'short_name' => 'CHE', 'state' => 'ANDHRA PRADESH'],
            ['name' => 'AMARAVATI', 'short_name' => 'AMR', 'state' => 'ANDHRA PRADESH'],
            ['name' => 'HINDUPUR', 'short_name' => 'HUP', 'state' => 'ANDHRA PRADESH'],

            // --- KERALA (32) ---
            ['name' => 'THIRUVANANTHAPURAM', 'short_name' => 'TRV', 'state' => 'KERALA'], // Trivandrum
            ['name' => 'KOCHI', 'short_name' => 'COK', 'state' => 'KERALA'], // Cochin / Ernakulam
            ['name' => 'KOZHIKODE', 'short_name' => 'CCJ', 'state' => 'KERALA'], // Calicut
            ['name' => 'KOLLAM', 'short_name' => 'QLN', 'state' => 'KERALA'], // Quilon
            ['name' => 'THRISSUR', 'short_name' => 'TCR', 'state' => 'KERALA'], // Trichur
            ['name' => 'KANNUR', 'short_name' => 'CNN', 'state' => 'KERALA'],
            ['name' => 'ALAPPUZHA', 'short_name' => 'ALP', 'state' => 'KERALA'], // Alleppey
            ['name' => 'KOTTAYAM', 'short_name' => 'KTM', 'state' => 'KERALA'],
            ['name' => 'PALAKKAD', 'short_name' => 'PGT', 'state' => 'KERALA'], // Palghat
            ['name' => 'MALAPPURAM', 'short_name' => 'MLP', 'state' => 'KERALA'],
            ['name' => 'MANJERI', 'short_name' => 'MJR', 'state' => 'KERALA'],
            ['name' => 'THALASSERY', 'short_name' => 'TLY', 'state' => 'KERALA'],
            ['name' => 'KASARAGOD', 'short_name' => 'KGQ', 'state' => 'KERALA'],
            ['name' => 'PATHANAMTHITTA', 'short_name' => 'PTA', 'state' => 'KERALA'],
            ['name' => 'WAYANAD', 'short_name' => 'WYD', 'state' => 'KERALA'], // Kalpetta
            ['name' => 'IDUKKI', 'short_name' => 'IDK', 'state' => 'KERALA'],
            ['name' => 'THIRUVALLA', 'short_name' => 'TVL', 'state' => 'KERALA'],

            // --- MADHYA PRADESH (23) ---
            ['name' => 'INDORE', 'short_name' => 'IDR', 'state' => 'MADHYA PRADESH'],
            ['name' => 'BHOPAL', 'short_name' => 'BPL', 'state' => 'MADHYA PRADESH'],
            ['name' => 'JABALPUR', 'short_name' => 'JBP', 'state' => 'MADHYA PRADESH'],
            ['name' => 'GWALIOR', 'short_name' => 'GWL', 'state' => 'MADHYA PRADESH'],
            ['name' => 'UJJAIN', 'short_name' => 'UJN', 'state' => 'MADHYA PRADESH'],
            ['name' => 'SAGAR', 'short_name' => 'SGR', 'state' => 'MADHYA PRADESH'],
            ['name' => 'DEWAS', 'short_name' => 'DWS', 'state' => 'MADHYA PRADESH'],
            ['name' => 'SATNA', 'short_name' => 'STA', 'state' => 'MADHYA PRADESH'],
            ['name' => 'RATLAM', 'short_name' => 'RTM', 'state' => 'MADHYA PRADESH'],
            ['name' => 'REWA', 'short_name' => 'RWA', 'state' => 'MADHYA PRADESH'],
            ['name' => 'KATNI', 'short_name' => 'KTE', 'state' => 'MADHYA PRADESH'],
            ['name' => 'SINGRAULI', 'short_name' => 'SGL', 'state' => 'MADHYA PRADESH'],
            ['name' => 'BURHANPUR', 'short_name' => 'BHP', 'state' => 'MADHYA PRADESH'],
            ['name' => 'KHANDWA', 'short_name' => 'KNW', 'state' => 'MADHYA PRADESH'],
            ['name' => 'BHIND', 'short_name' => 'BND', 'state' => 'MADHYA PRADESH'],
            ['name' => 'CHHINDWARA', 'short_name' => 'CWA', 'state' => 'MADHYA PRADESH'],
            ['name' => 'GUNA', 'short_name' => 'GNA', 'state' => 'MADHYA PRADESH'],
            ['name' => 'SHIVPURI', 'short_name' => 'SVP', 'state' => 'MADHYA PRADESH'],
            ['name' => 'VIDISHA', 'short_name' => 'VDS', 'state' => 'MADHYA PRADESH'],
            ['name' => 'CHHATARPUR', 'short_name' => 'CHT', 'state' => 'MADHYA PRADESH'],
            ['name' => 'DAMOH', 'short_name' => 'DMH', 'state' => 'MADHYA PRADESH'],
            ['name' => 'MANDSAUR', 'short_name' => 'MDS', 'state' => 'MADHYA PRADESH'],
            ['name' => 'KHARGONE', 'short_name' => 'KGN', 'state' => 'MADHYA PRADESH'],
            ['name' => 'NEEMUCH', 'short_name' => 'NMH', 'state' => 'MADHYA PRADESH'],
            ['name' => 'PITHAMPUR', 'short_name' => 'PTP', 'state' => 'MADHYA PRADESH'],
            ['name' => 'NARMADAPURAM', 'short_name' => 'NDP', 'state' => 'MADHYA PRADESH'], // Formerly Hoshangabad
            ['name' => 'ITARSI', 'short_name' => 'ET', 'state' => 'MADHYA PRADESH'],
            ['name' => 'SEHORE', 'short_name' => 'SHR', 'state' => 'MADHYA PRADESH'],
            ['name' => 'BETUL', 'short_name' => 'BTL', 'state' => 'MADHYA PRADESH'],
            ['name' => 'SEONI', 'short_name' => 'SNI', 'state' => 'MADHYA PRADESH'],
            ['name' => 'SHAHDOL', 'short_name' => 'SDL', 'state' => 'MADHYA PRADESH'],
            ['name' => 'MAIHAR', 'short_name' => 'MHR', 'state' => 'MADHYA PRADESH'],

            // --- PUNJAB (03) ---
            ['name' => 'LUDHIANA', 'short_name' => 'LDH', 'state' => 'PUNJAB'],
            ['name' => 'AMRITSAR', 'short_name' => 'ASR', 'state' => 'PUNJAB'],
            ['name' => 'JALANDHAR', 'short_name' => 'JUC', 'state' => 'PUNJAB'],
            ['name' => 'PATIALA', 'short_name' => 'PTA', 'state' => 'PUNJAB'],
            ['name' => 'BATHINDA', 'short_name' => 'BTI', 'state' => 'PUNJAB'],
            ['name' => 'MOHALI', 'short_name' => 'SAS', 'state' => 'PUNJAB'], // SAS Nagar
            ['name' => 'HOSHIARPUR', 'short_name' => 'HSP', 'state' => 'PUNJAB'],
            ['name' => 'BATALA', 'short_name' => 'BAT', 'state' => 'PUNJAB'],
            ['name' => 'PATHANKOT', 'short_name' => 'PTK', 'state' => 'PUNJAB'],
            ['name' => 'MOGA', 'short_name' => 'MOG', 'state' => 'PUNJAB'],
            ['name' => 'ABOHAR', 'short_name' => 'ABH', 'state' => 'PUNJAB'],
            ['name' => 'MALERKOTLA', 'short_name' => 'MLK', 'state' => 'PUNJAB'],
            ['name' => 'KHANNA', 'short_name' => 'KHN', 'state' => 'PUNJAB'],
            ['name' => 'PHAGWARA', 'short_name' => 'PGW', 'state' => 'PUNJAB'],
            ['name' => 'MUKTSAR', 'short_name' => 'MKT', 'state' => 'PUNJAB'],
            ['name' => 'BARNALA', 'short_name' => 'BNL', 'state' => 'PUNJAB'],
            ['name' => 'RAJPURA', 'short_name' => 'RJP', 'state' => 'PUNJAB'],
            ['name' => 'FIROZPUR', 'short_name' => 'FZR', 'state' => 'PUNJAB'],
            ['name' => 'KAPURTHALA', 'short_name' => 'KPT', 'state' => 'PUNJAB'],
            ['name' => 'SANGRUR', 'short_name' => 'SAG', 'state' => 'PUNJAB'],
            ['name' => 'FAZILKA', 'short_name' => 'FZK', 'state' => 'PUNJAB'],
            ['name' => 'GURDASPUR', 'short_name' => 'GDP', 'state' => 'PUNJAB'],
            ['name' => 'ZIRAKPUR', 'short_name' => 'ZRK', 'state' => 'PUNJAB'],

            // --- HARYANA (06) ---
            ['name' => 'GURUGRAM', 'short_name' => 'GGN', 'state' => 'HARYANA'], // Formerly Gurgaon
            ['name' => 'FARIDABAD', 'short_name' => 'FDB', 'state' => 'HARYANA'],
            ['name' => 'PANIPAT', 'short_name' => 'PNP', 'state' => 'HARYANA'],
            ['name' => 'AMBALA', 'short_name' => 'UMB', 'state' => 'HARYANA'],
            ['name' => 'YAMUNANAGAR', 'short_name' => 'YNR', 'state' => 'HARYANA'],
            ['name' => 'ROHTAK', 'short_name' => 'ROK', 'state' => 'HARYANA'],
            ['name' => 'HISAR', 'short_name' => 'HSR', 'state' => 'HARYANA'],
            ['name' => 'KARNAL', 'short_name' => 'KNL', 'state' => 'HARYANA'],
            ['name' => 'SONIPAT', 'short_name' => 'SNP', 'state' => 'HARYANA'],
            ['name' => 'PANCHKULA', 'short_name' => 'PKL', 'state' => 'HARYANA'],
            ['name' => 'BHIWANI', 'short_name' => 'BNW', 'state' => 'HARYANA'],
            ['name' => 'SIRSA', 'short_name' => 'SSA', 'state' => 'HARYANA'],
            ['name' => 'BAHADURGARH', 'short_name' => 'BDG', 'state' => 'HARYANA'],
            ['name' => 'JIND', 'short_name' => 'JND', 'state' => 'HARYANA'],
            ['name' => 'KURUKSHETRA', 'short_name' => 'KKR', 'state' => 'HARYANA'],
            ['name' => 'KAITHAL', 'short_name' => 'KTL', 'state' => 'HARYANA'],
            ['name' => 'REWARI', 'short_name' => 'REW', 'state' => 'HARYANA'],
            ['name' => 'PALWAL', 'short_name' => 'PLW', 'state' => 'HARYANA'],
            ['name' => 'MANESAR', 'short_name' => 'MNR', 'state' => 'HARYANA'],
            ['name' => 'JHAJJAR', 'short_name' => 'JHJ', 'state' => 'HARYANA'],

            // --- ODISHA (21) ---
            ['name' => 'BHUBANESWAR', 'short_name' => 'BBI', 'state' => 'ODISHA'],
            ['name' => 'CUTTACK', 'short_name' => 'CTC', 'state' => 'ODISHA'],
            ['name' => 'ROURKELA', 'short_name' => 'RRK', 'state' => 'ODISHA'],
            ['name' => 'BERHAMPUR', 'short_name' => 'BAM', 'state' => 'ODISHA'],
            ['name' => 'SAMBALPUR', 'short_name' => 'SBP', 'state' => 'ODISHA'],
            ['name' => 'PURI', 'short_name' => 'PRI', 'state' => 'ODISHA'],
            ['name' => 'BALASORE', 'short_name' => 'BLS', 'state' => 'ODISHA'],
            ['name' => 'BHADRAK', 'short_name' => 'BHK', 'state' => 'ODISHA'],
            ['name' => 'BARIPADA', 'short_name' => 'BPD', 'state' => 'ODISHA'],
            ['name' => 'JHARSUGUDA', 'short_name' => 'JSG', 'state' => 'ODISHA'],
            ['name' => 'JEYPORE', 'short_name' => 'JYP', 'state' => 'ODISHA'],
            ['name' => 'BARGARH', 'short_name' => 'BRG', 'state' => 'ODISHA'],
            ['name' => 'RAYAGADA', 'short_name' => 'RYG', 'state' => 'ODISHA'],
            ['name' => 'BOLANGIR', 'short_name' => 'BLG', 'state' => 'ODISHA'],
            ['name' => 'ANGUL', 'short_name' => 'ANGL', 'state' => 'ODISHA'],
            ['name' => 'PARADIP', 'short_name' => 'PRDP', 'state' => 'ODISHA'],
            ['name' => 'JAJPUR', 'short_name' => 'JJP', 'state' => 'ODISHA'],
            ['name' => 'KEONJHAR', 'short_name' => 'KJR', 'state' => 'ODISHA'],

            // --- JHARKHAND (20) ---
            ['name' => 'RANCHI', 'short_name' => 'RNC', 'state' => 'JHARKHAND'],
            ['name' => 'JAMSHEDPUR', 'short_name' => 'JSR', 'state' => 'JHARKHAND'], // Tatanagar
            ['name' => 'DHANBAD', 'short_name' => 'DHN', 'state' => 'JHARKHAND'],
            ['name' => 'BOKARO STEEL CITY', 'short_name' => 'BOK', 'state' => 'JHARKHAND'],
            ['name' => 'DEOGHAR', 'short_name' => 'DGH', 'state' => 'JHARKHAND'],
            ['name' => 'HAZARIBAGH', 'short_name' => 'HZB', 'state' => 'JHARKHAND'],
            ['name' => 'GIRIDIH', 'short_name' => 'GRD', 'state' => 'JHARKHAND'],
            ['name' => 'RAMGARH', 'short_name' => 'RMG', 'state' => 'JHARKHAND'],
            ['name' => 'MEDININAGAR', 'short_name' => 'MDN', 'state' => 'JHARKHAND'], // Daltonganj
            ['name' => 'CHAIBASA', 'short_name' => 'CBS', 'state' => 'JHARKHAND'],
            ['name' => 'DUMKA', 'short_name' => 'DMK', 'state' => 'JHARKHAND'],
            ['name' => 'GODDA', 'short_name' => 'GDA', 'state' => 'JHARKHAND'],
            ['name' => 'SAHIBGANJ', 'short_name' => 'SBG', 'state' => 'JHARKHAND'],
            ['name' => 'KODERMA', 'short_name' => 'KDR', 'state' => 'JHARKHAND'],
            ['name' => 'CHAS', 'short_name' => 'CHS', 'state' => 'JHARKHAND'],

            // --- CHHATTISGARH (22) ---
            ['name' => 'RAIPUR', 'short_name' => 'RPR', 'state' => 'CHHATTISGARH'],
            ['name' => 'BHILAI', 'short_name' => 'BHL', 'state' => 'CHHATTISGARH'],
            ['name' => 'BILASPUR (CG)', 'short_name' => 'BSP', 'state' => 'CHHATTISGARH'],
            ['name' => 'KORBA', 'short_name' => 'KRB', 'state' => 'CHHATTISGARH'],
            ['name' => 'DURG', 'short_name' => 'DRG', 'state' => 'CHHATTISGARH'],
            ['name' => 'RAJNANDGAON', 'short_name' => 'RJG', 'state' => 'CHHATTISGARH'],
            ['name' => 'JAGDALPUR', 'short_name' => 'JDP', 'state' => 'CHHATTISGARH'],
            ['name' => 'RAIGARH', 'short_name' => 'RGH', 'state' => 'CHHATTISGARH'],
            ['name' => 'AMBIKAPUR', 'short_name' => 'ABP', 'state' => 'CHHATTISGARH'],
            ['name' => 'DHAMTARI', 'short_name' => 'DMT', 'state' => 'CHHATTISGARH'],
            ['name' => 'MAHASAMUND', 'short_name' => 'MSM', 'state' => 'CHHATTISGARH'],
            ['name' => 'BHATAPARA', 'short_name' => 'BTP', 'state' => 'CHHATTISGARH'],

            // --- UTTARAKHAND (05) ---
            ['name' => 'DEHRADUN', 'short_name' => 'DDN', 'state' => 'UTTARAKHAND'],
            ['name' => 'HARIDWAR', 'short_name' => 'HW', 'state' => 'UTTARAKHAND'],
            ['name' => 'ROORKEE', 'short_name' => 'RK', 'state' => 'UTTARAKHAND'],
            ['name' => 'HALDWANI', 'short_name' => 'HDW', 'state' => 'UTTARAKHAND'],
            ['name' => 'RUDRAPUR', 'short_name' => 'RDP', 'state' => 'UTTARAKHAND'],
            ['name' => 'KASHIPUR', 'short_name' => 'KSP', 'state' => 'UTTARAKHAND'],
            ['name' => 'RISHIKESH', 'short_name' => 'RKH', 'state' => 'UTTARAKHAND'],
            ['name' => 'PANTNAGAR', 'short_name' => 'PTN', 'state' => 'UTTARAKHAND'],
            ['name' => 'NAINITAL', 'short_name' => 'NNT', 'state' => 'UTTARAKHAND'],
            ['name' => 'ALMORA', 'short_name' => 'ALM', 'state' => 'UTTARAKHAND'],
            ['name' => 'PITHORAGARH', 'short_name' => 'PTG', 'state' => 'UTTARAKHAND'],
            ['name' => 'KOTDWAR', 'short_name' => 'KDW', 'state' => 'UTTARAKHAND'],
            ['name' => 'MUSSOORIE', 'short_name' => 'MSR', 'state' => 'UTTARAKHAND'],
            ['name' => 'RAMNAGAR', 'short_name' => 'RMN', 'state' => 'UTTARAKHAND'],

            // --- HIMACHAL PRADESH (02) ---
            ['name' => 'SHIMLA', 'short_name' => 'SML', 'state' => 'HIMACHAL PRADESH'],
            ['name' => 'DHARAMSHALA', 'short_name' => 'DHM', 'state' => 'HIMACHAL PRADESH'],
            ['name' => 'SOLAN', 'short_name' => 'SLN', 'state' => 'HIMACHAL PRADESH'],
            ['name' => 'MANDI', 'short_name' => 'MND', 'state' => 'HIMACHAL PRADESH'],
            ['name' => 'BADDI', 'short_name' => 'BDD', 'state' => 'HIMACHAL PRADESH'],
            ['name' => 'KULLU', 'short_name' => 'KLU', 'state' => 'HIMACHAL PRADESH'],
            ['name' => 'MANALI', 'short_name' => 'MNL', 'state' => 'HIMACHAL PRADESH'],
            ['name' => 'UNA', 'short_name' => 'UNA', 'state' => 'HIMACHAL PRADESH'],
            ['name' => 'NAHAN', 'short_name' => 'NHN', 'state' => 'HIMACHAL PRADESH'],
            ['name' => 'HAMIRPUR (HP)', 'short_name' => 'HMR', 'state' => 'HIMACHAL PRADESH'],
            ['name' => 'BILASPUR (HP)', 'short_name' => 'BLS', 'state' => 'HIMACHAL PRADESH'],
            ['name' => 'CHAMBA', 'short_name' => 'CHM', 'state' => 'HIMACHAL PRADESH'],
            ['name' => 'PAONTA SAHIB', 'short_name' => 'PTS', 'state' => 'HIMACHAL PRADESH'],
            ['name' => 'PALAMPUR', 'short_name' => 'PLM', 'state' => 'HIMACHAL PRADESH'],
            ['name' => 'NALAGARH', 'short_name' => 'NLG', 'state' => 'HIMACHAL PRADESH'],

            // --- JAMMU AND KASHMIR (01) ---
            ['name' => 'SRINAGAR', 'short_name' => 'SXR', 'state' => 'JAMMU AND KASHMIR'],
            ['name' => 'JAMMU', 'short_name' => 'JAT', 'state' => 'JAMMU AND KASHMIR'],
            ['name' => 'ANANTNAG', 'short_name' => 'ANG', 'state' => 'JAMMU AND KASHMIR'],
            ['name' => 'BARAMULLA', 'short_name' => 'BRM', 'state' => 'JAMMU AND KASHMIR'],
            ['name' => 'KATHUA', 'short_name' => 'KTH', 'state' => 'JAMMU AND KASHMIR'],
            ['name' => 'UDHAMPUR', 'short_name' => 'UDH', 'state' => 'JAMMU AND KASHMIR'],
            ['name' => 'SOPORE', 'short_name' => 'SPR', 'state' => 'JAMMU AND KASHMIR'],
            ['name' => 'RAJOURI', 'short_name' => 'RJR', 'state' => 'JAMMU AND KASHMIR'],
            ['name' => 'POONCH', 'short_name' => 'PCH', 'state' => 'JAMMU AND KASHMIR'],
            ['name' => 'PULWAMA', 'short_name' => 'PLW', 'state' => 'JAMMU AND KASHMIR'],
            ['name' => 'KUPWARA', 'short_name' => 'KPW', 'state' => 'JAMMU AND KASHMIR'],
            ['name' => 'SAMBA', 'short_name' => 'SMB', 'state' => 'JAMMU AND KASHMIR'],
            ['name' => 'KATRA', 'short_name' => 'KTR', 'state' => 'JAMMU AND KASHMIR'],

            // --- LADAKH (38) ---
            ['name' => 'LEH', 'short_name' => 'LEH', 'state' => 'LADAKH'],
            ['name' => 'KARGIL', 'short_name' => 'KGL', 'state' => 'LADAKH'],
            ['name' => 'DISKIT', 'short_name' => 'DSK', 'state' => 'LADAKH'],
            ['name' => 'DRASS', 'short_name' => 'DRS', 'state' => 'LADAKH'],

            // --- GOA (30) ---
            ['name' => 'PANAJI', 'short_name' => 'PAN', 'state' => 'GOA'], // Panjim
            ['name' => 'MARGAO', 'short_name' => 'MAO', 'state' => 'GOA'], // Madgaon
            ['name' => 'VASCO DA GAMA', 'short_name' => 'VSG', 'state' => 'GOA'],
            ['name' => 'MAPUSA', 'short_name' => 'MPS', 'state' => 'GOA'],
            ['name' => 'PONDA', 'short_name' => 'PND', 'state' => 'GOA'],
            ['name' => 'BICHOLIM', 'short_name' => 'BCL', 'state' => 'GOA'],
            ['name' => 'PORVORIM', 'short_name' => 'PVR', 'state' => 'GOA'],

            // --- ARUNACHAL PRADESH (12) ---
            ['name' => 'ITANAGAR', 'short_name' => 'ITN', 'state' => 'ARUNACHAL PRADESH'],
            ['name' => 'NAHARLAGUN', 'short_name' => 'NHL', 'state' => 'ARUNACHAL PRADESH'],
            ['name' => 'PASIGHAT', 'short_name' => 'PSG', 'state' => 'ARUNACHAL PRADESH'],
            ['name' => 'TAWANG', 'short_name' => 'TWN', 'state' => 'ARUNACHAL PRADESH'],
            ['name' => 'ZIRO', 'short_name' => 'ZRO', 'state' => 'ARUNACHAL PRADESH'],
            ['name' => 'BANDERDEWA', 'short_name' => 'BDW', 'state' => 'ARUNACHAL PRADESH'],
            ['name' => 'BOMDILA', 'short_name' => 'BMD', 'state' => 'ARUNACHAL PRADESH'],
            ['name' => 'TEZU', 'short_name' => 'TEZ', 'state' => 'ARUNACHAL PRADESH'],
            ['name' => 'AALO', 'short_name' => 'ALO', 'state' => 'ARUNACHAL PRADESH'], // Along
            ['name' => 'ROING', 'short_name' => 'RNG', 'state' => 'ARUNACHAL PRADESH'],
            ['name' => 'NAMSAI', 'short_name' => 'NMS', 'state' => 'ARUNACHAL PRADESH'],
            ['name' => 'CHANGLANG', 'short_name' => 'CHG', 'state' => 'ARUNACHAL PRADESH'],
            ['name' => 'KHONSA', 'short_name' => 'KHS', 'state' => 'ARUNACHAL PRADESH'],
            ['name' => 'SEPPA', 'short_name' => 'SPA', 'state' => 'ARUNACHAL PRADESH'],
            ['name' => 'YINGKIONG', 'short_name' => 'YKG', 'state' => 'ARUNACHAL PRADESH'],
            ['name' => 'DAPORIJO', 'short_name' => 'DPJ', 'state' => 'ARUNACHAL PRADESH'],
            ['name' => 'BASAR', 'short_name' => 'BSR', 'state' => 'ARUNACHAL PRADESH'],
            ['name' => 'LONGDING', 'short_name' => 'LGD', 'state' => 'ARUNACHAL PRADESH'],

            // --- MEGHALAYA (17) ---
            ['name' => 'SHILLONG', 'short_name' => 'SHL', 'state' => 'MEGHALAYA'],
            ['name' => 'TURA', 'short_name' => 'TRA', 'state' => 'MEGHALAYA'],
            ['name' => 'JOWAI', 'short_name' => 'JWI', 'state' => 'MEGHALAYA'],
            ['name' => 'NONGPOH', 'short_name' => 'NPH', 'state' => 'MEGHALAYA'],
            ['name' => 'BYRNIHAT', 'short_name' => 'BYR', 'state' => 'MEGHALAYA'],
            ['name' => 'WILLIAMNAGAR', 'short_name' => 'WLN', 'state' => 'MEGHALAYA'],
            ['name' => 'BAGHMARA', 'short_name' => 'BGM', 'state' => 'MEGHALAYA'],
            ['name' => 'RESUBELPARA', 'short_name' => 'RSP', 'state' => 'MEGHALAYA'],
            ['name' => 'KHLIEHRIAT', 'short_name' => 'KHL', 'state' => 'MEGHALAYA'],
            ['name' => 'NONGSTOIN', 'short_name' => 'NST', 'state' => 'MEGHALAYA'],
            ['name' => 'CHERRAPUNJI', 'short_name' => 'CRP', 'state' => 'MEGHALAYA'], // Sohra
            ['name' => 'DAWKI', 'short_name' => 'DWK', 'state' => 'MEGHALAYA'],

            // --- TRIPURA (16) ---
            ['name' => 'AGARTALA', 'short_name' => 'AGT', 'state' => 'TRIPURA'],
            ['name' => 'DHARMANAGAR', 'short_name' => 'DMN', 'state' => 'TRIPURA'],
            ['name' => 'UDAIPUR (TRIPURA)', 'short_name' => 'UDP', 'state' => 'TRIPURA'],
            ['name' => 'KAILASHAHAR', 'short_name' => 'KLS', 'state' => 'TRIPURA'],
            ['name' => 'BELONIA', 'short_name' => 'BLN', 'state' => 'TRIPURA'],
            ['name' => 'KHOWAI', 'short_name' => 'KHW', 'state' => 'TRIPURA'],
            ['name' => 'TELIAMURA', 'short_name' => 'TLM', 'state' => 'TRIPURA'],
            ['name' => 'BISHALGARH', 'short_name' => 'BSG', 'state' => 'TRIPURA'],
            ['name' => 'AMBASSA', 'short_name' => 'AMB', 'state' => 'TRIPURA'],
            ['name' => 'SABROOM', 'short_name' => 'SBR', 'state' => 'TRIPURA'],
            ['name' => 'KUMARGHAT', 'short_name' => 'KMG', 'state' => 'TRIPURA'],

            // --- MIZORAM (15) ---
            ['name' => 'AIZAWL', 'short_name' => 'AZL', 'state' => 'MIZORAM'],
            ['name' => 'LUNGLEI', 'short_name' => 'LGL', 'state' => 'MIZORAM'],
            ['name' => 'CHAMPHAI', 'short_name' => 'CMP', 'state' => 'MIZORAM'],
            ['name' => 'SERCHHIP', 'short_name' => 'SRC', 'state' => 'MIZORAM'],
            ['name' => 'KOLASIB', 'short_name' => 'KLB', 'state' => 'MIZORAM'],
            ['name' => 'LAWNGTLAI', 'short_name' => 'LTL', 'state' => 'MIZORAM'],
            ['name' => 'SIAHA', 'short_name' => 'SIH', 'state' => 'MIZORAM'],
            ['name' => 'MAMIT', 'short_name' => 'MMT', 'state' => 'MIZORAM'],
            ['name' => 'VAIRENTE', 'short_name' => 'VRT', 'state' => 'MIZORAM'],

            // --- MANIPUR (14) ---
            ['name' => 'IMPHAL', 'short_name' => 'IMP', 'state' => 'MANIPUR'],
            ['name' => 'CHURACHANDPUR', 'short_name' => 'CCP', 'state' => 'MANIPUR'],
            ['name' => 'THOUBAL', 'short_name' => 'THB', 'state' => 'MANIPUR'],
            ['name' => 'KAKCHING', 'short_name' => 'KKC', 'state' => 'MANIPUR'],
            ['name' => 'UKHRUL', 'short_name' => 'UKH', 'state' => 'MANIPUR'],
            ['name' => 'SENAPATI', 'short_name' => 'SNP', 'state' => 'MANIPUR'],
            ['name' => 'BISHNUPUR', 'short_name' => 'BNP', 'state' => 'MANIPUR'],
            ['name' => 'JIRIBAM', 'short_name' => 'JRB', 'state' => 'MANIPUR'],
            ['name' => 'MOREH', 'short_name' => 'MRH', 'state' => 'MANIPUR'],
            ['name' => 'TAMENGLONG', 'short_name' => 'TML', 'state' => 'MANIPUR'],

            // --- NAGALAND (13) ---
            ['name' => 'DIMAPUR', 'short_name' => 'DMP', 'state' => 'NAGALAND'],
            ['name' => 'KOHIMA', 'short_name' => 'KOH', 'state' => 'NAGALAND'],
            ['name' => 'MOKOKCHUNG', 'short_name' => 'MKG', 'state' => 'NAGALAND'],
            ['name' => 'TUENSANG', 'short_name' => 'TSG', 'state' => 'NAGALAND'],
            ['name' => 'WOKHA', 'short_name' => 'WKH', 'state' => 'NAGALAND'],
            ['name' => 'ZUNHEBOTO', 'short_name' => 'ZHB', 'state' => 'NAGALAND'],
            ['name' => 'MON', 'short_name' => 'MON', 'state' => 'NAGALAND'],
            ['name' => 'PHEK', 'short_name' => 'PHK', 'state' => 'NAGALAND'],
            ['name' => 'CHUMOUKEDIMA', 'short_name' => 'CKD', 'state' => 'NAGALAND'],
            ['name' => 'MEDZIPHEMA', 'short_name' => 'MZP', 'state' => 'NAGALAND'],

            // --- SIKKIM (11) ---
            ['name' => 'GANGTOK', 'short_name' => 'GTK', 'state' => 'SIKKIM'],
            ['name' => 'NAMCHI', 'short_name' => 'NMC', 'state' => 'SIKKIM'],
            ['name' => 'GEYZING', 'short_name' => 'GYZ', 'state' => 'SIKKIM'],
            ['name' => 'MANGAN', 'short_name' => 'MGN', 'state' => 'SIKKIM'],
            ['name' => 'RANGPO', 'short_name' => 'RGP', 'state' => 'SIKKIM'],
            ['name' => 'SINGTAM', 'short_name' => 'SGT', 'state' => 'SIKKIM'],
            ['name' => 'JORETHANG', 'short_name' => 'JRT', 'state' => 'SIKKIM'],

            // --- CHANDIGARH (04) ---
            ['name' => 'CHANDIGARH', 'short_name' => 'IXC', 'state' => 'CHANDIGARH'],

            // --- PUDUCHERRY (34) ---
            ['name' => 'PUDUCHERRY', 'short_name' => 'PNY', 'state' => 'PUDUCHERRY'],
            ['name' => 'KARAIKAL', 'short_name' => 'KRK', 'state' => 'PUDUCHERRY'],
            ['name' => 'MAHE', 'short_name' => 'MAH', 'state' => 'PUDUCHERRY'],
            ['name' => 'YANAM', 'short_name' => 'YNM', 'state' => 'PUDUCHERRY'],

            // --- ANDAMAN AND NICOBAR ISLANDS (35) ---
            ['name' => 'PORT BLAIR', 'short_name' => 'IXZ', 'state' => 'ANDAMAN AND NICOBAR ISLANDS'],
            ['name' => 'DIGLIPUR', 'short_name' => 'DGP', 'state' => 'ANDAMAN AND NICOBAR ISLANDS'],

            // --- DADRA AND NAGAR HAVELI AND DAMAN AND DIU (26) ---
            ['name' => 'DAMAN', 'short_name' => 'DMN', 'state' => 'DAMAN AND DIU'],
            ['name' => 'DIU', 'short_name' => 'DIU', 'state' => 'DAMAN AND DIU'],
            ['name' => 'SILVASSA', 'short_name' => 'SLV', 'state' => 'DADRA AND NAGAR HAVELI'],

            // --- LAKSHADWEEP (31) ---
            ['name' => 'KAVARATTI', 'short_name' => 'KVT', 'state' => 'LAKSHADWEEP'],
            ['name' => 'AGATTI', 'short_name' => 'AGX', 'state' => 'LAKSHADWEEP'],
        ];

        // Truncate and insert all cities with foreign key mapping
        DB::table('cities')->truncate();

        $insertedCount = 0;
        foreach ($allCities as $c) {
            $stateId = $stateMap[$c['state']] ?? null;
            DB::table('cities')->insert([
                'state_id'   => $stateId,
                'name'       => $c['name'],
                'short_name' => $c['short_name'],
                'created_at' => now(),
                'updated_at' => now(),
            ]);
            $insertedCount++;
        }

        Schema::enableForeignKeyConstraints();
    }
}
